<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Table_history_connected_tmp_model extends CI_Model
{

    public $table = 'table_history_connected_tmp';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,uuid_summary,idtoko,namatoko,jam_play,menit_play,date_input');
        // $this->datatables->where('id,uuid_summary,idtoko,namatoko,jam_play,menit_play,date_input');
        $this->datatables->from('table_history_connected_tmp');
        //add this line for join
        //$this->datatables->join('table2', 'table_history_connected_tmp.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('table_history_connected_tmp/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('table_history_connected_tmp/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('table_history_connected_tmp/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('uuid_summary', $q);
	$this->db->or_like('idtoko', $q);
	$this->db->or_like('namatoko', $q);
	$this->db->or_like('jam_play', $q);
	$this->db->or_like('menit_play', $q);
	$this->db->or_like('date_input', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('uuid_summary', $q);
	$this->db->or_like('idtoko', $q);
	$this->db->or_like('namatoko', $q);
	$this->db->or_like('jam_play', $q);
	$this->db->or_like('menit_play', $q);
	$this->db->or_like('date_input', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Table_history_connected_tmp_model.php */
/* Location: ./application/models/Table_history_connected_tmp_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-06-22 05:08:56 */
/* http://harviacode.com */