<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_user_model extends CI_Model
{

    public $table_lupapassword = 'tbl_user_lupapassword';
    public $table = 'tbl_user';
    public $id = 'id_users';
    public $full_name = 'full_name';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_users', $q);
        $this->db->or_like('uuid_users', $q);
        $this->db->or_like('date_input', $q);
        $this->db->or_like('full_name', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('images', $q);
        $this->db->or_like('id_user_level', $q);
        $this->db->or_like('is_aktif', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_users', $q);
        $this->db->or_like('uuid_users', $q);
        $this->db->or_like('date_input', $q);
        $this->db->or_like('full_name', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('images', $q);
        $this->db->or_like('id_user_level', $q);
        $this->db->or_like('is_aktif', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function get_data_role_admin($limit, $start = 0, $q = NULL)
    {
        $full_name="admin";

        $this->db->order_by($this->id, $this->order);
        $this->db->where($this->full_name, $full_name);
        
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    function insert_tbl_user_lupapassword($data)
    {
        $this->db->insert($this->table_lupapassword, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Tbl_user_model.php */
/* Location: ./application/models/Tbl_user_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-04-03 02:32:50 */
/* http://harviacode.com */